### ISSUE TITLE
作为一个爱国者，应该自觉主动完成学习强国，而不是使用外挂

### ISSUE THREAD

**Issue by 78qw5ojhj** [Dunky-Z/Dunky-Z.github.io#2]
要亲自观看，亲自完成
![](https://pbs.twimg.com/media/FC3EUf3WEAE-Pd_.jpg)

**Comment by Dunky-Z** [comment]
> 要亲自观看，亲自完成 ![](https://camo.githubusercontent.com/9ea13c75825682ac3c58e84d37fa897c05bac6092b0d130384d9cacb5ba6c6ec/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f46433345556633574541452d50645f2e6a7067)

你眼睛长得都跟蜗牛似的，看不到我每篇都亲自看完吗？哦？难道你说我star了js脚本？难道js脚本不能学习？难道每个人都跟你这个蛙族一样，到GitHub只会散播蛙族言论么？
